# Scaffolding generated by Casein v5.2.0.0

module Casein
  class EventsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]

    def index
      @casein_page_title = 'Events'
      @events = Event.order(sort_order(:date)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View event'
      @event = Event.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new event'
      @event = Event.new
    end

    def create
      @event = Event.new event_params
      @event.max_bookings = ((@event.end_time - @event.start_time) / 60) / @event.slot_duration_minutes
      if @event.save
        # create empty slots to let the users book:
        create_slots
        flash[:notice] = 'Event created'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new event'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update event'

      @event = Event.find params[:id]

      if @event.update_attributes event_params
        flash[:notice] = 'Event has been updated'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to update this event'
        render action: :show
      end
    end

    def destroy
      @event = Event.find params[:id]

      @event.destroy
      flash[:notice] = 'Event has been deleted'
      redirect_to casein_events_path
    end

    private

    def event_params
      params.require(:event).permit(:name, :date, :location, :description, :max_bookings, :price_per_slot, :start_time, :end_time, :slot_duration_minutes)
    end

    def create_slots
      slot_start_time = @event.start_time
      # event_slot_duration will be added to slot_start_time to set each slot's start_time
      # -- it's "* 60" because times are updated in seconds
      event_slot_duration = @event.slot_duration_minutes * 60
      @event.max_bookings.times do
        Slot.create(event: @event, start_time: slot_start_time)
        slot_start_time += event_slot_duration
      end
    end

  end
end
