# Scaffolding generated by Casein v5.2.0.0

module Casein
  class UsersController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Users'
      @users = User.order(sort_order(:first_name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View user'
      @user = User.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new user'
      @user = User.new
    end

    def create
      @user = User.new user_params

      if @user.save
        flash[:notice] = 'User created'
        redirect_to casein_users_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new user'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update user'

      @user = User.find params[:id]

      if @user.update_attributes user_params
        flash[:notice] = 'User has been updated'
        redirect_to casein_users_path
      else
        flash.now[:warning] = 'There were problems when trying to update this user'
        render action: :show
      end
    end

    def destroy
      @user = User.find params[:id]

      @user.destroy
      flash[:notice] = 'User has been deleted'
      redirect_to casein_users_path
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :provider)
    end
  end
end
